package ChatClientRMI;

/**
* ChatClientRMI/ChatUserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatUser.idl
* Sunday, December 12, 2010 3:30:45 PM EST
*/

public final class ChatUserHolder implements org.omg.CORBA.portable.Streamable
{
  public ChatClientRMI.ChatUser value = null;

  public ChatUserHolder ()
  {
  }

  public ChatUserHolder (ChatClientRMI.ChatUser initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ChatClientRMI.ChatUserHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ChatClientRMI.ChatUserHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ChatClientRMI.ChatUserHelper.type ();
  }

}
