package ChatClientRMI;


/**
* ChatClientRMI/ChatUserPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatUser.idl
* Sunday, December 12, 2010 3:30:45 PM EST
*/

public abstract class ChatUserPOA extends org.omg.PortableServer.Servant
 implements ChatClientRMI.ChatUserOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("updateMessage", new java.lang.Integer (0));
    _methods.put ("updateLocation", new java.lang.Integer (1));
    _methods.put ("updateUserList", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ChatClientRMI/ChatUser/updateMessage
       {
         this.updateMessage ();
         out = $rh.createReply();
         break;
       }

       case 1:  // ChatClientRMI/ChatUser/updateLocation
       {
         this.updateLocation ();
         out = $rh.createReply();
         break;
       }

       case 2:  // ChatClientRMI/ChatUser/updateUserList
       {
         this.updateUserList ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ChatClientRMI/ChatUser:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ChatUser _this() 
  {
    return ChatUserHelper.narrow(
    super._this_object());
  }

  public ChatUser _this(org.omg.CORBA.ORB orb) 
  {
    return ChatUserHelper.narrow(
    super._this_object(orb));
  }


} // class ChatUserPOA
