package ChatClientRMI;


/**
* ChatClientRMI/ChatUserOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ChatUser.idl
* Sunday, December 12, 2010 3:30:45 PM EST
*/

public interface ChatUserOperations 
{
  void updateMessage ();
  void updateLocation ();
  void updateUserList ();
} // interface ChatUserOperations
