// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler v1.6a_p8 ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be\be_codegen.cpp:381


#include "ChatRoomC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/AnyTypeCode/String_TypeCode_Static.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "ChatRoomC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be\be_visitor_arg_traits.cpp:73

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_interface/interface_cs.cpp:60

// Traits specializations for ChatRoom.

ChatRoom_ptr
TAO::Objref_Traits<ChatRoom>::duplicate (
    ChatRoom_ptr p)
{
  return ChatRoom::_duplicate (p);
}

void
TAO::Objref_Traits<ChatRoom>::release (
    ChatRoom_ptr p)
{
  ::CORBA::release (p);
}

ChatRoom_ptr
TAO::Objref_Traits<ChatRoom>::nil (void)
{
  return ChatRoom::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<ChatRoom>::marshal (
    const ChatRoom_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// Function pointer for collocation factory initialization.
TAO::Collocation_Proxy_Broker * 
(*_TAO_ChatRoom_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  ) = 0;

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_cs.cpp:78

::CORBA::Boolean ChatRoom::connect (
    const char * nickname,
    ::CORBA::Long avatarCode)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_ChatRoom_Proxy_Broker_ == 0)
    {
      ChatRoom_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::ACE_InputCDR::to_boolean>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Char *>::in_arg_val _tao_nickname (nickname);
  TAO::Arg_Traits< ::CORBA::Long>::in_arg_val _tao_avatarCode (avatarCode);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_nickname,
      &_tao_avatarCode
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      3,
      "connect",
      7,
      this->the_TAO_ChatRoom_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_cs.cpp:78

::CORBA::Boolean ChatRoom::disconnect (
    const char * nickname)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_ChatRoom_Proxy_Broker_ == 0)
    {
      ChatRoom_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::ACE_InputCDR::to_boolean>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Char *>::in_arg_val _tao_nickname (nickname);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_nickname
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "disconnect",
      10,
      this->the_TAO_ChatRoom_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_cs.cpp:78

void ChatRoom::sendMessage (
    char *& message,
    const char * fromNickname)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_ChatRoom_Proxy_Broker_ == 0)
    {
      ChatRoom_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Char *>::inout_arg_val _tao_message (message);
  TAO::Arg_Traits< ::CORBA::Char *>::in_arg_val _tao_fromNickname (fromNickname);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_message,
      &_tao_fromNickname
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      3,
      "sendMessage",
      11,
      this->the_TAO_ChatRoom_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_cs.cpp:78

::CORBA::Boolean ChatRoom::sendMessageToParty (
    const char * message,
    const char * fromNickname,
    const char * toNickname)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_ChatRoom_Proxy_Broker_ == 0)
    {
      ChatRoom_setup_collocation ();
    }
  
  TAO::Arg_Traits< ::ACE_InputCDR::to_boolean>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Char *>::in_arg_val _tao_message (message);
  TAO::Arg_Traits< ::CORBA::Char *>::in_arg_val _tao_fromNickname (fromNickname);
  TAO::Arg_Traits< ::CORBA::Char *>::in_arg_val _tao_toNickname (toNickname);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_message,
      &_tao_fromNickname,
      &_tao_toNickname
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      4,
      "sendMessageToParty",
      18,
      this->the_TAO_ChatRoom_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_cs.cpp:78

void ChatRoom::sendLocation (
    ::CORBA::Long x,
    ::CORBA::Long y,
    const char * fromNickname)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_ChatRoom_Proxy_Broker_ == 0)
    {
      ChatRoom_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Long>::in_arg_val _tao_x (x);
  TAO::Arg_Traits< ::CORBA::Long>::in_arg_val _tao_y (y);
  TAO::Arg_Traits< ::CORBA::Char *>::in_arg_val _tao_fromNickname (fromNickname);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_x,
      &_tao_y,
      &_tao_fromNickname
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      4,
      "sendLocation",
      12,
      this->the_TAO_ChatRoom_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
}

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_operation/operation_cs.cpp:78

void ChatRoom::sendUserList (
    const char * toNickname)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_ChatRoom_Proxy_Broker_ == 0)
    {
      ChatRoom_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Char *>::in_arg_val _tao_toNickname (toNickname);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_toNickname
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "sendUserList",
      12,
      this->the_TAO_ChatRoom_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0);
}

ChatRoom::ChatRoom (void)
 : the_TAO_ChatRoom_Proxy_Broker_ (0)
{
  this->ChatRoom_setup_collocation ();
}

void
ChatRoom::ChatRoom_setup_collocation ()
{
  if (::_TAO_ChatRoom_Proxy_Broker_Factory_function_pointer)
    {
      this->the_TAO_ChatRoom_Proxy_Broker_ =
        ::_TAO_ChatRoom_Proxy_Broker_Factory_function_pointer (this);
    }
}

ChatRoom::~ChatRoom (void)
{}

void 
ChatRoom::_tao_any_destructor (void *_tao_void_pointer)
{
  ChatRoom *_tao_tmp_pointer =
    static_cast<ChatRoom *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

ChatRoom_ptr
ChatRoom::_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<ChatRoom>::narrow (
        _tao_objref,
        "IDL:ChatRoom:1.0",
        _TAO_ChatRoom_Proxy_Broker_Factory_function_pointer
      );
}

ChatRoom_ptr
ChatRoom::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<ChatRoom>::unchecked_narrow (
        _tao_objref,
        "IDL:ChatRoom:1.0",
        _TAO_ChatRoom_Proxy_Broker_Factory_function_pointer
      );
}

ChatRoom_ptr
ChatRoom::_duplicate (ChatRoom_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

void
ChatRoom::_tao_release (ChatRoom_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
ChatRoom::_is_a (const char *value)
{
  if (
      !ACE_OS::strcmp (
          value,
          "IDL:ChatRoom:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* ChatRoom::_interface_repository_id (void) const
{
  return "IDL:ChatRoom:1.0";
}

::CORBA::Boolean
ChatRoom::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_typecode/objref_typecode.cpp:76

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_ChatRoom (
    ::CORBA::tk_objref,
    "IDL:ChatRoom:1.0",
    "ChatRoom");
  
::CORBA::TypeCode_ptr const _tc_ChatRoom =
  &_tao_tc_ChatRoom;

// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_interface/any_op_cs.cpp:51
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<ChatRoom>::to_object (
      ::CORBA::Object_ptr &_tao_elem
    ) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    ChatRoom_ptr _tao_elem)
{
  ChatRoom_ptr _tao_objptr =
    ChatRoom::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    ChatRoom_ptr *_tao_elem)
{
  TAO::Any_Impl_T<ChatRoom>::insert (
      _tao_any,
      ChatRoom::_tao_any_destructor,
      _tc_ChatRoom,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    ChatRoom_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<ChatRoom>::extract (
        _tao_any,
        ChatRoom::_tao_any_destructor,
        _tc_ChatRoom,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// c:\ace_wrappers\tao\tao_idl\be\be_visitor_interface/cdr_op_cs.cpp:63

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const ChatRoom_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    ChatRoom_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;
  
  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::ChatRoom RHS_SCOPED_NAME;
  
  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        _TAO_ChatRoom_Proxy_Broker_Factory_function_pointer
      );
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



