// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler v1.6a_p8 ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from 
// be\be_codegen.cpp:1198

#include "ChatRoomI.h"

// Implementation skeleton constructor
ChatRoom_i::ChatRoom_i (void)
{
}

// Implementation skeleton destructor
ChatRoom_i::~ChatRoom_i (void)
{
}

::CORBA::Boolean ChatRoom_i::connect (
    const char * nickname,
    ::CORBA::Long avatarCode)
{
  // Add your implementation here
}

::CORBA::Boolean ChatRoom_i::disconnect (
    const char * nickname)
{
  // Add your implementation here
}

void ChatRoom_i::sendMessage (
    char *& message,
    const char * fromNickname)
{
  // Add your implementation here
}

::CORBA::Boolean ChatRoom_i::sendMessageToParty (
    const char * message,
    const char * fromNickname,
    const char * toNickname)
{
  // Add your implementation here
}

void ChatRoom_i::sendLocation (
    ::CORBA::Long x,
    ::CORBA::Long y,
    const char * fromNickname)
{
  // Add your implementation here
}

void ChatRoom_i::sendUserList (
    const char * toNickname)
{
  // Add your implementation here
}


